### ISSUE TITLE
Heueristic Miner does not recogize key in parameter dict

### ISSUE THREAD

**Issue by 13bmartens** [pm4py/pm4py-source#108]
Hi Guys,
I am encountering a strange error when attempting to use the heuristic miner on a custom pandas dataframe.
Version: 1.1.27
Dataframe:
WorkItemId|ChangedBy|WorkItemType|AssumedCountry|Department|ChangedDate|State

Function Call:
`heu_net = heuristics_miner.apply(df,  parameters={'case_id_glue':'WorkItemId','activity_key':'Department','timestamp_key':'ChangedDate'})`

Error Message:
```
Traceback (most recent call last):
  File "C:\Users\XXXXXXX\AppData\Local\Continuum\anaconda3\envs\PMENV\lib\site-packages\pandas\core\indexes\base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'concept:name'
```
Is this due to an oversight on my part or a bug?
Your help is greatly appreciated.
-Ben

**Comment by Javert899** [comment]
Hello,

Try to use the following parameters specification:


from pm4py.objects.log.importer.parquet import factory as parquet_importer
from pm4py.algo.discovery.heuristics import factory as heuristics_miner
from pm4py.util import constants
from pm4py.visualization.petrinet import factory as pn_vis_factory

df = parquet_importer.apply("C:\\running-example.parquet")
net, im, fm = heuristics_miner.apply(df, parameters={constants.PARAMETER_CONSTANT_CASEID_KEY: "case:concept:name",
                                                     constants.PARAMETER_CONSTANT_ACTIVITY_KEY: "concept:name",
                                                     constants.PARAMETER_CONSTANT_TIMESTAMP_KEY: "time:timestamp"})
gviz = pn_vis_factory.apply(net, im, fm)
pn_vis_factory.view(gviz)

**Comment by 13bmartens** [comment]
Thanks for the tip, the custom dataframe works now!
